// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtpD8_HbrrRDV4s2EkJxek9NFwKBsUX7w',
    appId: '1:464453045778:web:16b776314a549db6df92cb',
    messagingSenderId: '464453045778',
    projectId: 'fooddelivery-9e03b',
    authDomain: 'fooddelivery-9e03b.firebaseapp.com',
    storageBucket: 'fooddelivery-9e03b.appspot.com',
    measurementId: 'G-GWFZ7EV366',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClsAv3A460pbVB4sFnZbYEHQhDFxaBtEQ',
    appId: '1:464453045778:android:e643b8397a76c968df92cb',
    messagingSenderId: '464453045778',
    projectId: 'fooddelivery-9e03b',
    storageBucket: 'fooddelivery-9e03b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMaAfu4u0HFMlBoozVhp7ZaPx8UmOgDWU',
    appId: '1:464453045778:ios:de6a47f980ebf41adf92cb',
    messagingSenderId: '464453045778',
    projectId: 'fooddelivery-9e03b',
    storageBucket: 'fooddelivery-9e03b.appspot.com',
    androidClientId: '464453045778-8lk2f5gn0pln3g7f4a3apou52b3n3vbd.apps.googleusercontent.com',
    iosClientId: '464453045778-k6foc6mq3itog65ipp2v2j92iqui5c9g.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMaAfu4u0HFMlBoozVhp7ZaPx8UmOgDWU',
    appId: '1:464453045778:ios:de6a47f980ebf41adf92cb',
    messagingSenderId: '464453045778',
    projectId: 'fooddelivery-9e03b',
    storageBucket: 'fooddelivery-9e03b.appspot.com',
    androidClientId: '464453045778-8lk2f5gn0pln3g7f4a3apou52b3n3vbd.apps.googleusercontent.com',
    iosClientId: '464453045778-k6foc6mq3itog65ipp2v2j92iqui5c9g.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliveryApp',
  );
}
